---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Keeposz/nas-pi-cluster.git
    path: deployments/media/jellyfin
    targetRevision: HEAD
    helm:
      releaseName: jellyfin
      valuesObject:
        jellyfin:
          podSecurityContext:
            runAsUser: 1000
            runAsGroup: 100
            fsGroup: 100

          service:
            type: LoadBalancer
            port: 8096

          ingress:
            enabled: true
            className: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
              traefik.ingress.kubernetes.io/router.entrypoints: websecure
              traefik.ingress.kubernetes.io/router.tls: "true"
            hosts:
              - host: jellyfin.home.keeposz.dev
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: jellyfin-tls
                hosts:
                  - jellyfin.home.keeposz.dev

          resources:
            requests:
              memory: "384Mi"
              cpu: "300m"
            limits:
              memory: "1536Mi"
              cpu: "1500m"

          persistence:
            config:
              enabled: true
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: local-path
            media:
              enabled: false
            cache:
              enabled: true
              type: pvc
              accessMode: ReadWriteOnce
              size: 10Gi
              storageClass: local-path

          jellyfin:
            env:
              - name: JELLYFIN_PublishedServerUrl
                value: "https://jellyfin.home.keeposz.dev"
              - name: JELLYFIN_CACHE_DIR
                value: /cache
              - name: TZ
                value: "Europe/Brussels"

          volumes:
            - name: films
              hostPath:
                path: /srv/dev-disk-by-uuid-db0fba78-7fcc-48a0-8554-9f4d3f445363/NAS-PI/PLEX/FILMS
            - name: series
              hostPath:
                path: /srv/dev-disk-by-uuid-db0fba78-7fcc-48a0-8554-9f4d3f445363/NAS-PI/PLEX/SERIES

          volumeMounts:
            - name: films
              mountPath: /data/films
              readOnly: true
            - name: series
              mountPath: /data/series
              readOnly: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: media
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
