---
apiVersion: v2
appVersion: "1.0"
description: Jellyfin Media Server
name: jellyfin
version: "1.0"
dependencies:
  - name: jellyfin
    version: "3.2.0"
    repository: https://jellyfin.github.io/jellyfin-helm
