---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCF1de09J73mJfXhYZhXY7ssnMLb2hrbQGwmW7F8HoVRYUiOQP6t2K3VNpl7hRu3X6M+ynKOYeTh/QpXLe67nydJEEclKHMsqen1Mp2w6a9WP+lTYVt4kcoV5In9ZXZc+sd9aUKd4tVJaAowNH1VF1DTFpChT3E7kkrmA/y7yAWRZ/JhxoMy/fya2yWjeBH7+GVpeXFbjQ9IRCfJONJc64/k62zw+NEDRbhIt3F3RhooOYbZXVR+Zyl2cSPqLOoeMfEyciw5NlAdEiOYTqRrGRTPC37CJWYMmaV0fCs/MClB3McG0qXyChroBIDuD1mrywj9wKPMF7JHutYA3JB0p0+WzMfJB6niv6SvfbgbCXoY8UujbMiWFr4n1hm29Zi0JIJ6ecaamr2L/CFslPO2qB6h/PnARlV4F9zzgr5qDadX+WkgFuGVnmiQdjpvhrM63QLjLAbWsTEHqi/Aj1iEMlG13Xsgl/VSnG57L3JLyPh4o5c6Q6LzHN9tE0FblvkpeaRk7LU8okyydYt1lj2HbJ2ID6Hx2VVQdSJ6ch3ucrubQMj4J/xqhpT6p0CWXFgii5laNcUWgrUO4JGq9i8ZaDT18ef9roN4mX8+69hm0wCpzak2C/R2vCPW+yPfCp25UDYsedF0t2bMYLS2KJdRZFt7FqaWkSWiQyjkHynUOeFAjub2r4f/j/zXFPyGqz88l97CK0J9dwrO/gee9u/5UsFGO23Uc9iDGDayg0Or46Wr50cvlVNpLVQ
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
