---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stirling-pdf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Keeposz/nas-pi-cluster.git
    path: deployments/stirling-pdf
    targetRevision: HEAD
    helm:
      releaseName: stirling-pdf
      valuesObject:
        stirling-pdf-chart:
          livenessProbe:
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
          readinessProbe:
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 5
          ingress:
            enabled: true
            className: traefik
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hosts:
              - host: pdf.home.keeposz.dev
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: stirling-pdf-tls
                hosts:
                  - pdf.home.keeposz.dev
  destination:
    server: "https://kubernetes.default.svc"
    namespace: stirling-pdf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
