---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    auth-key: <SEALED_VALUE>
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
