---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  encryptedData:
    auth-key: AgBMLRaE397xgcXcgtl2EG7yUE0v6XWOKWYgpKGYbupJGAiG+OatPgd+2Ot5WwishGHRUBcBvUb0sURhd1kDuYON2edttOoBJ5BooLezNucIXfxxcxjpAm1iTO3cSLXSTvJXLudp0Amm2KthpkmbOWOBICZvPCyF5oLjYOA8nPj2ml2UnfkAiNrT2CCGdW0htSYkYh9wgJn1Sy0nCSZ0yBKODdXiIwJkvKvJSEeK/X7V3Arekre5kA8cBaZcmfVEFce+9BNKf1jAuiCCBsy9mxpYmKqQPWQDyQLMF822iUu+GuUkrsCa1rlGjJG0GmI0OcHmyNkb8wO9r3BY80VGOpvSyMdb1OTdH4qmOe41roeSD5GUaPj1HjnSaEXNF9gOimKHpYSU7rGHb799u/MHaNNzf+sQK6wPwsgBhBUEQrjGfpY4OkjMDQ1yM2+RMjGc85D7FfrzbVuMlJ4GNDyFyvXbWSY7M6iLpyZv96fMBhNbg8JfralbkMNtk8KIOgWdznELuRqCOdFVNmyW7I70lt4osqz0KZsGwjwt8ITo9a9z+WiIP8oksgRm7cRo5qkDr+yOmggem5/EmjyuTmXrc/CtEOCoMC+z4ySVd+xQJigYy9M3QB7OQdKBspCB/udCRVVU/WRFONba0W2jITcW6bgsvYg7qBBT6UBnzfJZHoCC5tMgTlrkQm6FowWpmt+LZ5Ubh9aJYuKzSwUHIwQdLXc/yKyzpgGHusAeKRxhRW/uDrloa4fbw4LHRLk45xYmzvDCNrIdxCFlG8m+gPRA6Q==
  template:
    metadata:
      name: tailscale-auth
      namespace: tailscale
