---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: <SEALED_VALUE>
  template:
    metadata:
      name: grafana-admin
      namespace: observability
