---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCwxWbmBXsbPS/JkRkin8o5Uhgwf4Pz0M/QYKR+qfHoKIdjoIS9wVf8GY51oUM6rIu1Oa3ACbuYz7kO4osZbJSyGq7jbNfUvuGE66c9j/L0reA7qCTSuF8fLAv6Uy6vqgbflUB60a/worAWm2uqfetDHga3v29B9wU5TfvbpgzV7JftF9Ufhjf8ZgbWUYYGXmOJs3Cu0z3qMXJEPG8dyoX7dUt8dLnh3R2OBtQC0+dIjnTeF1xXeSziIIuLMT6Zytti1D9cH9QlsA38KY8uayjKCcPPeFRZxisyuYEdxFDiqTq0BpgWK1y8wvaWvHVTFxInUTx8lCOXgQByA3mV8diCsu8okEU5OWHs8DXEMvo4l/JmYIGdDirA1+Qcut9LL/A/Akzg86CiFAyEk0NkX1TCTWM3EP9SrJPA4iQEj2yfWaxhisrBI8SD1I4sTvEgJ+lbyrze9ogGJ8YskbJzgHg44xkgKufBWiK7w5ajvwGCtIrSAzlgNWp5zaH8ypJtCCE9VmRe2Shx79Wr/eBm4A5aB+7qa5WhBCLF58HJWxuumU3nEnUN7KN4lT1foKhnWEmqh04IAPhHU9s+KXdj5nzehQ2u/Lu/7ZS7VeQDpFELJfqeoqQTSUF0kp0LohP3gj5OCx/sn+DBhHb7kMSakiBNkUbJAIfWxgK7c+1X3G82USoNYmJNfpECSzHT+nARGLrO/Ohb59HTAUWw6Qbsug==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
