---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Keeposz/nas-pi-cluster.git
    path: deployments/websites/homepage
    targetRevision: HEAD
    helm:
      releaseName: homepage
  destination:
    server: "https://kubernetes.default.svc"
    namespace: homepage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
