---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate-operator-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Keeposz/nas-pi-cluster.git
    path: deployments/renovate-operator/renovate-operator-config
    targetRevision: HEAD
    helm:
      releaseName: renovate-operator-config
  destination:
    server: "https://kubernetes.default.svc"
    namespace: renovate-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
