---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-wg
  namespace: media
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgBpCfANpXRM+xIU0OLwBtet0NeDIM59ob3/P8K2wq4u3CDo/VcxZnW2fjauIv0lrgtwOVrL5EJ4pCTsYYgCVMYX64PuClvaRHQpszBH4QIw3qEzvpdn6h1yJRoKRF4vCH3cbwYyn6zo+X4PyueXXb6+XnuPXzj384ziIqy7kOwgcLc7ZYP7m8sLzXVUg1+szkGBGb2BZA3i1k9oXknjtffmvZDUmoved4QUGHgXZadraXcdfOiuI8ANetyfsho7cPPmA4pmK9EeGEUfnTn6dOvsXU1Pf93eMSm2624x19SM++5ZbJqCwanxbKdcv7w49C3ytbdTe2HMVLSEdS04Vw0NJ1wUZ8hNls1EkiofNb1tG1Zj7OZ87dNSecYQt/BcyoMsUyHJTsTjtmdoz8uYAne1CKH5ByEnLdbvrbOjkU4sCvfJDBtap0CH3NnCPOIHteYFF7FO5MUNIcLTSXVaVoEYGnvEyrRqRqUP/O1EcMmMGnnH9wEOAi3dLtH8nTw47GOQwt7gB7ZXG6h6lII46fX+5cCx5XAYWHEs1VLJVHUC/3YTB1x9PplG3b4lwtFn6wsym5LkG4o6+xN12b/cfLoA7ZFAurbkWUSdqZLHPDFU9NEX+rA9NNzWeyRkwdJ2Hs3Vo7CyMyo/uxLdCXtACzTYibrZxBAmXPDgU6xPCK3fJk2kXphTYg7GCjZlftRKqTnxlhYIWBnkuYqHl/8N5USyVsDv5mz0NpIcSB+tqp/OCLMNfOOU9SjQhpY5aw==
  template:
    metadata:
      name: gluetun-wg
      namespace: media
