---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Keeposz/nas-pi-cluster.git
    path: deployments/cert-manager/cert-manager
    targetRevision: HEAD
    helm:
      releaseName: cert-manager
      valuesObject:
        cert-manager:
          installCRDs: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
