---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDU3sQ5nvbsGv7e74mBnIDwXRq1QBUjNRpeX7r+phFFuPr+xUcAfCTFZ703rp3PyN6EBA8UMO/bw1YA5Itll1Gxrkba9nm61zc1+vz71uCsen7vwENbgV8BGu6PxuM/c7ea35EJ1Nk9mexjuyz9/9piC/4ylYXgvxnqjQqiOEXgfV9Tz4Uie4ZWPnSk0A/t6kdag7aIXIFQFtWVlj1wcgOHX1llLBUG16d0hlcaOcbQfdedQhmu+9FpJr+HyBquMK4y7I95OCEJdzjwZq7DwDN/vME0039ts8MaWP/OOX9q025zuncmKX84o7nxhJBKoYkpcteSEX/EUVzZ7om52tEIg2V3QasDANttohCdEAcoyWc3FdtiqArzRmBfkBDWzmhe3I/L5S/t2YUURSJ3T+zsPR0BL3y144sX6YED67D4TrXZkhSY5fwRCh5vKdm5UnDgtFAd18d3aNpM747KE9lNkjwLv1+i5pPv5JnnQdBXWajdW5gc73Bs0HsIovuZizI7algi7XKx0Gn+3WorNHKK3g1OLUvhXrPbjBj3Az6vD3kjPSb6ksBj6g1gSKJAOKMDjNm4/WG1I8Dsdolv6BVCi0rQND7Ho+ZLiWn8vYHr/0cwqrabR5izJLbCT3cmCD4Mr+YB4hSHqZSpWNx9N4hjBzpwrBmwKcl17nrfP8q7tYlwmHrl2fGErJxp7a7WN57tYgx/ThW1yMAIvgt1TH9W7WZMRf7o4Qti/Xz47/pPvSRLf0ISThjV
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
