---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gluetun-wg
  namespace: media
spec:
  encryptedData:
    WIREGUARD_PRIVATE_KEY: AgC341lMVk6wv7sNatfhhqU/GmnmgJo9mR3Q4KgsFIo4VRV9bUPHf84Un7JXk4tu6u7/WqqpOZVKe1R1d0XPYoWfp7o1plap7OhFZ85lA2FbppOelK0qT+wHUmW9FpgIPzMvtSQRfEg28Oy5skmVp2NvD5MMsuQxdC9ZIsL/yLyGVC28zYcjbe/z14zDKdPC4sveKGHswFiuKTTTp/vSow7qUqMicparb4ACJIa0dp4/quo9Mn/uO7trrH3WDKiisCsvZoKtYuCuBrIMnJws+DTuJuiWYlhGyYuxZ+sV6Qp08r3lp4VL8yaf8ZaaPYyXvss0mAW3xX0FLm8CNfTeg7K4h/IEXuRmPwyn4ehCCoH/8Y5WR6Q8QmI7MIdtLLUdmMhbCjcSJ8TCiFwblQpA+3vN9fE6ip1UvAabTo9HV89tAt3pytOOvZL+EQydCRG5zyVV1/Dk6w34YMKZVmsOs2YnTjO/quI72465bCGByPLsN/GC+CtidetFIR/1bIVU5r/GTOqvbOGNO3PWiY36rWVrYFc1x/rDnICxkbgx4Strwl9S2xvDsijTr0Rv8EqhRs8HQP1HYrKrJEU4QzQXa58wKojy4UK7IPmd3JsuBfAw4bVc4FR/223Q8+osvFai7KjR3JAHRYtP6o/OcEPZfm9bFRSpK1AAJfQ/umEw4bwATCTGKfO6RVOXZ/3kmom/Kd4fIVjqDjDo0RrLez91h8qENG92PSKCO7XqVFD8movPfE62vnt8+B5EkqhlmPg=
  template:
    metadata:
      name: gluetun-wg
      namespace: media
