---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glances
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Keeposz/nas-pi-cluster.git
    path: deployments/glances/glances
    targetRevision: HEAD
    helm:
      releaseName: glances
  destination:
    server: "https://kubernetes.default.svc"
    namespace: glances
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
